# Generated by Django 4.1.7 on 2023-02-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
