# Generated by Django 4.1.7 on 2023-02-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_catergory',
            new_name='variation_category',
        ),
    ]
