# Generated by Django 4.1.7 on 2023-03-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_variation_created_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variation',
            managers=[
            ],
        ),
    ]
